"""
QQ email notification — sends daily strategy summary via SMTP.

Config via .env file (NOT committed to git):
  QQ_EMAIL=your_qq@qq.com
  QQ_AUTH_CODE=your_smtp_auth_code
  TO_EMAIL=recipient@qq.com
"""

from __future__ import annotations

import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)

ENV_FILE = Path(__file__).resolve().parent.parent.parent / ".env"


def _load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def send_daily_report(subject: str, body_html: str) -> bool:
    """Send report via QQ mail SMTP."""

    env = _load_env()
    sender = env.get("QQ_EMAIL", os.environ.get("QQ_EMAIL", ""))
    auth_code = env.get("QQ_AUTH_CODE", os.environ.get("QQ_AUTH_CODE", ""))
    receiver = env.get("TO_EMAIL", os.environ.get("TO_EMAIL", sender))

    if not sender or not auth_code:
        logger.error("QQ_EMAIL or QQ_AUTH_CODE not configured. Create .env file.")
        return False

    msg = MIMEMultipart("alternative")
    msg["From"] = sender
    msg["To"] = receiver
    msg["Subject"] = subject
    msg.attach(MIMEText(body_html, "html", "utf-8"))

    try:
        with smtplib.SMTP_SSL("smtp.qq.com", 465, timeout=15) as server:
            server.login(sender, auth_code)
            server.sendmail(sender, receiver, msg.as_string())
        logger.info("Email sent to %s", receiver)
        return True
    except Exception as e:
        logger.error("Failed to send email: %s", e)
        return False


def build_daily_email_body(
    date_str: str,
    trades: list[dict],
    account_summary: dict,
    signals_summary: dict[str, int],
) -> str:
    """Build HTML email body with today's report."""

    trade_rows = ""
    for t in trades:
        row_color = "#e8f5e9" if t["action"] == "buy" else "#fce4ec"
        trade_rows += f"""<tr style="background:{row_color}">
            <td>{t.get('code','')}</td><td>{t['action']}</td>
            <td>{t.get('shares',0)}</td><td>{t.get('price',0)}</td><td>{t.get('value',0):.2f}</td></tr>"""

    signal_rows = ""
    for sname, count in sorted(signals_summary.items(), key=lambda x: -x[1]):
        signal_rows += f"<tr><td>{sname}</td><td>{count}</td></tr>"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body{{font-family:'Segoe UI',sans-serif;margin:20px;background:#f5f5f5}}
.card{{background:#fff;border-radius:8px;padding:16px;margin:12px 0;box-shadow:0 2px 4px rgba(0,0,0,0.1)}}
h2{{color:#333;margin:0 0 8px 0}}table{{border-collapse:collapse;width:100%}}
th{{background:#4472C4;color:#fff;padding:8px;text-align:center}}
td{{padding:6px;text-align:center;border-bottom:1px solid #eee}}
.good{{color:#2e7d32;font-weight:bold}}.bad{{color:#c62828;font-weight:bold}}
</style></head><body>
<h1>量化策略日报</h1>
<p>日期: {date_str} | 生成时间: {datetime.now().strftime('%H:%M')}</p>

<div class="card"><h2>账户概览</h2>
<table><tr><th>总资产</th><th>现金</th><th>持仓数</th><th>累计收益</th></tr>
<tr><td class="good">{account_summary.get('total_value',0):,.2f}</td>
<td>{account_summary.get('cash',0):,.2f}</td>
<td>{account_summary['position_count']}</td>
<td class="{'good' if account_summary.get('total_return_pct',0) >= 0 else 'bad'}">{account_summary.get('total_return_pct',0):+.2f}%</td></tr></table></div>

<div class="card"><h2>今日信号</h2>
<table><tr><th>策略</th><th>信号数</th></tr>{signal_rows}</table></div>

<div class="card"><h2>今日交易</h2>
<table><tr><th>代码</th><th>方向</th><th>数量</th><th>价格</th><th>金额</th></tr>{trade_rows}</table></div>

<p style="color:#999;font-size:12px">Generated by quant-strategy-verification</p>
</body></html>"""
